### ISSUE TITLE
OCP Labs are hidden and require fixes

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt.github.io#273] opened 2019-06-26 14:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

OCP Labs are in the source code for website, but not listed on https://kubevirt.io/labs/kubernetes/lab1.html

When updating _data/labs_toc.yml to list them they now appear, but require some other fixes as there are broken links to images that are no longer there

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**Anything else we need to know?**:

> URL where the problem can be found ... 
> If the issue is with a lab, please provide information about your environment, platform, versions, ...

**Comment by codificat** [comment] 2019-06-26 14:30
@iranzo this is related to (if not a duplicate of) #254

**Comment by iranzo** [comment] 2019-06-26 14:32
Closed as duplicated of #254

**Closed** 2019-06-26 14:32 UTC
Labels: kind/bug
